### ISSUE TITLE
Move non-essential types to cdist-extra

### ISSUE THREAD

**Issue by sideeffect42** [cdist-community/cdist-conf#2]
Decide which types belong into cdist core and which ones should be moved to cdist-extra.
I'm proposing the following:

in **cdist-conf** stay:
- global explorers (obviously)
- ubiquitous types (`__file`, `__directory`, `__link`, `__package`, `__cdistmarker`, `__check_messages` etc.)
- types used to configure common parts of the operating system (`__cron`, `__user`, `__locale`, `__timezone`, `__start_on_boot` etc.)
- OS-specific but very common types (e.g. `__sshd_config`, `__ssh_authorized_keys` et al, `__apt_source`, `__apt_key`, `__yum_repo`, `__systemd_service`, `__uci_*` etc.)

moved to **cdist-extra**:
- highly specific configuration for certain applications (e.g. `__xymon_*`, `__prometheus_*`, `__haproxy_dualstack`, `__grafana_dashboard`, `__docker_*` etc.)
- badly maintained types

There will be a grey area where decisions need to be discussed, e.g. `__postgres_*` (although PostgreSQL is very common, not every machine is a database server).

**Comment by sideeffect42** [comment]
| Type                            | Repo                        |
|---------------------------------|:--------------------------  |
| __acl                           | cdist-conf                  |
| __apt_backports                 | cdist-conf                  |
| __apt_default_release           | cdist-conf                  |
| __apt_key                       | cdist-conf                  |
| __apt_key_uri                   | cdist-conf                  |
| __apt_mark                      | cdist-conf                  |
| __apt_norecommends              | cdist-conf                  |
| __apt_pin                       | cdist-conf                  |
| __apt_ppa                       | cdist-conf                  |
| __apt_source                    | cdist-conf                  |
| __apt_unattended_upgrades       | cdist-conf                  |
| __apt_update_index              | cdist-conf                  |
| __block                         | cdist-conf                  |
| __ccollect_source               | **cdist-extra**             |
| __cdist                         | ?                           |
| __cdistmarker                   | cdist-conf                  |
| __check_messages                | cdist-conf                  |
| __chroot_mount                  | ?                           |
| __chroot_umount                 | ?                           |
| __clean_path                    | cdist-conf                  |
| __config_file                   | **cdist-extra**[^config]    |
| __consul                        | **cdist-extra**             |
| __consul_agent                  | **cdist-extra**             |
| __consul_check                  | **cdist-extra**             |
| __consul_reload                 | **cdist-extra**             |
| __consul_service                | **cdist-extra**             |
| __consul_template               | **cdist-extra**             |
| __consul_template_template      | **cdist-extra**             |
| __consul_watch_checks           | **cdist-extra**             |
| __consul_watch_event            | **cdist-extra**             |
| __consul_watch_key              | **cdist-extra**             |
| __consul_watch_keyprefix        | **cdist-extra**             |
| __consul_watch_nodes            | **cdist-extra**             |
| __consul_watch_service          | **cdist-extra**             |
| __consul_watch_services         | **cdist-extra**             |
| __cron                          | cdist-conf                  |
| __daemontools                   | **cdist-extra**             |
| __daemontools_service           | **cdist-extra**             |
| __debconf_set_selections        | **cdist-extra**             |
| __directory                     | cdist-conf                  |
| __docker                        | **cdist-extra**             |
| __docker_compose                | **cdist-extra**             |
| __docker_config                 | **cdist-extra**             |
| __docker_secret                 | **cdist-extra**             |
| __docker_stack                  | **cdist-extra**             |
| __docker_swarm                  | **cdist-extra**             |
| __dog_vdi                       | **cdist-extra**             |
| __dot_file                      | ?                           |
| __download                      | cdist-conf                  |
| __dpkg_architecture             | cdist-conf                  |
| __file                          | cdist-conf                  |
| __filesystem                    | **cdist-extra**[^dangerous]   |
| __firewalld_rule                | ?                           |
| __firewalld_start               | ?                           |
| __git                           | cdist-conf                  |
| __go_get                        | **cdist-extra**             |
| __golang_from_vendor            | **cdist-extra**             |
| __grafana_dashboard             | **cdist-extra**             |
| __group                         | cdist-conf                  |
| __haproxy_dualstack             | **cdist-extra**             |
| __hostname                      | cdist-conf                  |
| __hosts                         | cdist-conf                  |
| __hwclock                       | cdist-conf                  |
| __install_bootloader_grub       | **cdist-extra**[^install]   |
| __install_chroot_mount          | **cdist-extra**[^install]   |
| __install_chroot_umount         | **cdist-extra**[^install]   |
| __install_config                | **cdist-extra**[^install]   |
| __install_coreos                | **cdist-extra**[^install]   |
| __install_directory             | **cdist-extra**[^install]   |
| __install_file                  | **cdist-extra**[^install]   |
| __install_fstab                 | **cdist-extra**[^install]   |
| __install_generate_fstab        | **cdist-extra**[^install]   |
| __install_mkfs                  | **cdist-extra**[^install]   |
| __install_mount                 | **cdist-extra**[^install]   |
| __install_partition_msdos       | **cdist-extra**[^install]   |
| __install_partition_msdos_apply | **cdist-extra**[^install]   |
| __install_reboot                | **cdist-extra**[^install]   |
| __install_reset_disk            | **cdist-extra**[^install]   |
| __install_stage                 | **cdist-extra**[^install]   |
| __install_umount                | **cdist-extra**[^install]   |
| __iptables_apply                | ?                           |
| __iptables_rule                 | ?                           |
| __issue                         | **cdist-extra**[^bad]       |
| __jail                          | ?                           |
| __jail_freebsd10                | ?                           |
| __jail_freebsd9                 | ?                           |
| __key_value                     | cdist-conf                  |
| __keyboard                      | **cdist-extra**[^bad]       |
| __letsencrypt_cert              | ?                           |
| __line                          | cdist-conf                  |
| __link                          | cdist-conf                  |
| __locale                        | cdist-conf                  |
| __locale_system                 | cdist-conf                  |
| __localedef                     | cdist-conf                  |
| __motd                          | cdist-conf                  |
| __mount                         | cdist-conf                  |
| __mysql_database                | ?                           |
| __mysql_privileges              | ?                           |
| __mysql_user                    | ?                           |
| __openldap_server               | ?                           |
| __package                       | cdist-conf                  |
| __package_apk                   | cdist-conf                  |
| __package_apt                   | cdist-conf                  |
| __package_dpkg                  | cdist-conf                  |
| __package_emerge                | cdist-conf                  |
| __package_emerge_dependencies   | cdist-conf                  |
| __package_luarocks              | cdist-conf                  |
| __package_opkg                  | cdist-conf                  |
| __package_pacman                | cdist-conf                  |
| __package_pip                   | cdist-conf                  |
| __package_pkg_freebsd           | cdist-conf                  |
| __package_pkg_openbsd           | cdist-conf                  |
| __package_pkgng_freebsd         | cdist-conf                  |
| __package_rubygem               | cdist-conf                  |
| __package_update_index          | cdist-conf                  |
| __package_upgrade_all           | cdist-conf                  |
| __package_yum                   | cdist-conf                  |
| __package_zypper                | cdist-conf                  |
| __pacman_conf                   | cdist-conf                  |
| __pacman_conf_integrate         | cdist-conf                  |
| __pf_apply_anchor               | ?                           |
| __pf_ruleset                    | ?                           |
| __ping                          | **cdist-extra**             |
| __postfix                       | ?                           |
| __postfix_master                | ?                           |
| __postfix_postconf              | ?                           |
| __postfix_postmap               | ?                           |
| __postfix_reload                | ?                           |
| __postgres_conf                 | ?                           |
| __postgres_database             | ?                           |
| __postgres_extension            | ?                           |
| __postgres_role                 | ?                           |
| __process                       | ?                           |
| __prometheus_alertmanager       | **cdist-extra**             |
| __prometheus_exporter           | **cdist-extra**             |
| __prometheus_server             | **cdist-extra**             |
| __pyvenv                        | ?                           |
| __qemu_img                      | ?                           |
| __rbenv                         | ?                           |
| __rsync                         | ?                           |
| __rvm                           | ?                           |
| __rvm_gem                       | ?                           |
| __rvm_gemset                    | ?                           |
| __rvm_ruby                      | ?                           |
| __sed                           | ?                           |
| __sensible_editor               | cdist-conf                  |
| __service                       | **cdist-extra**[^imp]       |
| __snakeoil_cert                 | **cdist-extra**             |
| __ssh_authorized_key            | cdist-conf                  |
| __ssh_authorized_keys           | cdist-conf                  |
| __ssh_dot_ssh                   | cdist-conf                  |
| __sshd_config                   | cdist-conf                  |
| __staged_file                   | cdist-conf                  |
| __start_on_boot                 | cdist-conf                  |
| __sysctl                        | cdist-conf                  |
| __systemd_service               | cdist-conf                  |
| __systemd_unit                  | cdist-conf                  |
| __timezone                      | cdist-conf                  |
| __uci                           | cdist-conf                  |
| __uci_section                   | cdist-conf                  |
| __ufw                           | ?                           |
| __ufw_rule                      | ?                           |
| __unpack                        | cdist-conf                  |
| __update_alternatives           | cdist-conf                  |
| __user                          | cdist-conf                  |
| __user_groups                   | cdist-conf                  |
| __xymon_apache                  | **cdist-extra**             |
| __xymon_client                  | **cdist-extra**             |
| __xymon_config                  | **cdist-extra**             |
| __xymon_server                  | **cdist-extra**             |
| __yum_repo                      | cdist-conf                  |
| __zypper_repo                   | ?                           |
| __zypper_service                | ?                           |

[^bad]: badly maintained
[^config]: or delete altogether? `__file` has `--onchange` too
[^dangerous]: not actively maintained and potentially dangerous (could eat your data)
[^install]: or remove, depends on cdist-community/cdist#1
[^imp]: Type is imperative (bad style).

**Comment by 4nd3r** [comment]
Edited your post.

Case for `__pyvenv` - using it together with `__package_pip` is, at least for me, very common. Especially for some time, because pip will display warning, if you install packages system-wide, because it's good practice to use virtual envs.

`__rsync` and `__sed` are arguable, but they are basically advanced versions of `__directory`, `__file`, `__line` etc.

`__jail*` types should be merged into one or moved to extra, so I vote for extra at the moment.

**Comment by sideeffect42** [comment]
> Edited your post.

YES, thanks.

> Case for `__pyvenv` - using it together with `__package_pip` is, at least for me, very common. Especially for some time, because pip will display warning, if you install packages system-wide, because it's good practice to use virtual envs.

Agreed.

> `__rsync` and `__sed` are arguable, but they are basically advanced versions of `__directory`, `__file`, `__line` etc.

The names at least sound useful :-)

> `__jail*` types should be merged into one or moved to extra, so I vote for extra at the moment.

I agree with -extra.  
Even if the types are merged into one it seems a bit of a niche use case to me.

> `__zypper_*` are go together with `__package_zypper`.

I was skeptical about `__zypper_*` because the code quality didn't really impress me too much.
But this concern also applies to other types, so let's keep them together.

> `__ufw*` are specific too... well, ufw. Just like `__iptables*` and `__pf*`.

Now that I have looked at these types more closely: clearly -extra.

`__iptables*` tries to invent its own rule management, `__pf_ruleset` is singleton (i.e. it can only install a single FW ruleset once) and `__ufw`, which would be the only one having a sane interface, isn't idempotent.

> `__cdist` to museum or we need to improve it. It shouldn't create a user etc.

I have to say that I don't see the use case for this type.
To use it you need to have cdist already installed, so where do you want to install cdist then?
Is this some self-hosting thing?

> `__dot_file` feels useful for preconfiguring user `$HOME`s.

All it does is creating parent directories owned by a specific user and call `__file`.  
I'd put it in -extra. If someone needs it, it's still available, but I don't think that it's useful enough for a variety of users to keep it in -core. 

> `__process` is weird beast, put it to museum for now (together with `__start_on_boot`), but if you feel different, then we can leave it to conf.

I agree with moving `__process` to -museum, but I use `__start_on_boot` very often, so I'd like to keep it in -conf.

I have many `__package`+`__start_on_boot` combinations in my manifests.
> `__mysql*`, `__postgres*` and `__postfix*` to extra, because specific to one application.

These would be good examples to make use of "bundles".

> For `__chroot_*` I feel that we are missing here something. How do you actually execute commands in cdist using cdist? Related to preos?

There's also `__install_chroot_*` versions.  
I can't see how these types would be useful without something that's missing in core.

Let's revisit them when we have decided what to do with `__install_*` and move them at the same place.

> `__qemu_img` to museum, because I don't see any use for it. Unless you mount it and use it like you would use `__chroot`, but... again, some preos stuff?

Maybe it could be used to create disk images for your VMs, but then again you would need something to manage VMs with which is missing.
I agree with museum. If someone can find a need for it, it can always be resurrected.

> Don't know about ruby stuff, my ruby-fu is very-very low.

RVM is a clusterfuck. For that reason alone `__rvm*` should go to -extra.
rbenv is saner, but IMO it's more of a specialty -> -extra.

**Comment by sideeffect42** [comment]
What doesn't make sense to me is that `__sensible_editor` can stay in -core but `__debconf_set_selections` ought to be migrated to -extra.  
I'd argue that both manage somewhat niche Debian features.

Other than that the list is complete and seems reasonable to me.
