### ISSUE TITLE
__package_pip: undo `--extras` deprecation

### ISSUE THREAD

**Issue by Matze1224** [cdist-community/cdist-conf#34]
In `__package_pip`, the parameter `--extras` was deprecated in #31 cause of unifying parameters:
> > deprecate --extra?
>
> When we have one --requirement to rule them all I think it would only be consequent to do so.

After writing writing with @4nd3r about this in [#cdist:ungleich.ch](https://matrix.to/#/#cdist:ungleich.ch) (around 12:58-13:52 GMT+2), we came to the conclusion, that at least some of the parts are required that the type can function as same as before.

The extras mechanism currently does the following:
1. Checks via `explorer/extras` which given `--extras` aren't currently installed and outputs all extras, that aren't fully installed
2. Installs the extras from the explorers (that currently aren't fully installed)

Point 1 is required that extras can be added after the package is fully installed. Removing is out of scope, as pip don't support the cleanup of unreferenced packages (like `apt autoremove`). Point 2 is the cherry on the cake, but completely useless as it's no different for pip if all extras are directly passed to pip instead of the extra filter for completely installed extras.

The newly introduced `--requirement`, which doesn't completely replace the deprecated `--name` (see `explorer/state` at least), should also be checked and parsed. Because it's also possible to pass extras with it, it should also be parsed in `explorer/state` to benefit of the explorer.

Possible things to do:
- [ ] undo `--extras` deprecation
- [ ] restore `--extras` examples in man
- [ ] support, discard or keep the current state of extras in `--requirement`
- [ ] rework `explorer/extras` comments if I get to touch it for the changes

**Comment by sideeffect42** [comment]
Extracting the extras from a `--requirement` is probably not easy, also Pip isn't really known for its stable interfaces.

So reintroducting `--extra` is probably the way to go.
But then this would mean that `--requirement` is basically reduced to being `--name` with another strange name :-(

**Comment by 4nd3r** [comment]
> Extracting the extras from a `--requirement` is probably not easy

```
$ echo 'foo[bar,baz,kaka]' | awk '{if(match($0,"\[[^\[\]]+\]$")){print substr($0,RSTART+1,RLENGTH-2)}}' | sed 's/,/\n/g'
bar
baz
kaka
```

tho, not sure about portability.

> also Pip isn't really known for its stable interfaces.

How long this `foo[bar,baz]` have been going on? IMHO long enough.

**Comment by sideeffect42** [comment]
AFAICR the `lib[extras]` syntax was present in Pip for a long time, but that doesn't mean anything.

Pip change their CLI output formats [unnecessarily](https://datenrei.ch/blog/2018/07/31/restore-pip-18-legacy-format.html), can't decide for a [project structure](https://pyquestions.com/proper-way-to-parse-requirements-file-after-pip-upgrade-to-pip-10-x-x) they like which is especially annoying because they don't provide a library for the basic functions (like parsing their own `requirements.txt`) or one day to install a package from a URL you use `git://somewhere#egg=foo` and on the next day it's `foo@git://somewhere`.

As you can probably guess I'm not the biggest fan of Pip, but given their instability and unpredictably moves I would refrain from trying to parse a Pip requirement using a regex.

I wrote an explorer for a private type some time ago that checks if all the requirements from a `requirements.txt` are already installed. It uses Pip internal functions for parsing the file and checking for installed packages satisfying a requirement.

Maybe it can also check for extras. I'll give it a try and report back.

**Comment by sideeffect42** [comment]
Maybe it's easier than expected: `pkg_resources.require` takes a requirement string as an argument and raises an exception if the requirement is not met.

e.g.
```console
$ pip list
Package    Version
---------- -------
pip        22.0.4
setuptools 47.1.0
$ pip install requests
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Installing collected packages: certifi, urllib3, idna, charset-normalizer, requests
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.12 idna-3.3 requests-2.27.1 urllib3-1.26.9
$ python -c 'import pkg_resources; pkg_resources.require("requests")'
$ echo $?
0
$ python -c 'import pkg_resources; pkg_resources.require("requests[socks]")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/t/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/private/tmp/t/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,>=1.5.6; extra == "socks"' distribution was not found and is required by requests
$ echo $?
1
$ pip install requests[socks]
Requirement already satisfied: requests[socks] in ./t/lib/python3.7/site-packages (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./t/lib/python3.7/site-packages (from requests[socks]) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in ./t/lib/python3.7/site-packages (from requests[socks]) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./t/lib/python3.7/site-packages (from requests[socks]) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./t/lib/python3.7/site-packages (from requests[socks]) (1.26.9)
Collecting PySocks!=1.5.7,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: PySocks
Successfully installed PySocks-1.7.1
$ python -c 'import pkg_resources; pkg_resources.require("requests[socks]")'
$ echo $?
0
```
