### ISSUE TITLE
Deprecate __package_update_index and __package_upgrade_all

### ISSUE THREAD

**Issue by sideeffect42** [cdist-community/cdist-conf#7]
This is a follow-up to #5.

After giving it some thought, I think we should move `__package_update_index` and `__package_upgrade_all` to [-museum](/cdist-community/cdist-museum), or at least [-extra](/cdist-community/cdist-extra).  
Both types only support a subset (APT, APK, Pacman, YUM) of package managers supported by cdist types.

These types don't really fit well with the design of cdist.
cdist's job is managing configuration, updating local caches or packages isn't configuration.
Moreover, since cdist is agent-less, it can be run infrequently, possibly leaving systems in an unupgraded state for a long time.

Keeping a system up-to-date should be solved via some other means (e.g. unattended-upgrades on Debian, apk-cron on Alpine, a cron job).

As far as `__package_update_index` is concerned, it might be necessary to update local package indexes prior to installing new packages:
* `__package_apt`: implements the refreshing logic itself.
* `__package_apk`: requires refreshing the local cache.  
  This could be handled in the type by adding `--cache-max-age` to the option list.
* `__package_pacman`:  requires refreshing the local cache.
  This could be handled in the type by adding `--refresh` to the option list.
  Then pacman will ask the mirror if it has a newer version of the file, and if so download it prior to installing the package.
  The process is fairly quick.
* `__package_yum`: noop.

**Comment by 4nd3r** [comment]
`__package_upgrade_all` - I agree, upgrading packages isn't configuration and there are better tools for that. To the museum.

`__package_update_index` - We agreed on that alreay, to the museum.

So, in the light of this idea that every `__package_*` type should deal with cache updating itself, if possible, so `__apt_update_index` too?

**Comment by sideeffect42** [comment]
> `__package_upgrade_all` - I agree, upgrading packages isn't configuration and there are better tools for that. To the museum.
> 
> `__package_update_index` - We agreed on that already, to the museum.

I updated #2.

> So, in the light of this idea that every `__package_*` type should deal with cache updating itself, if possible, so `__apt_update_index` too?

One could argue that updating the local index and installing packages are separate processes and should thus be separate types.

In any case, I think that it should be handled consistently for all package managers.
I'll make a new issue for this issue.

**Comment by 4nd3r** [comment]
oups, my mistake.

**Comment by sideeffect42** [comment]
Both types have been moved to cdist-museum (cdist-community/cdist-museum#1).
